import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ApolloClientProvider from "@/apollo/ApolloClientProvider";
import { AuthProvider } from "./hook/context/authContext";
import Header from "../components/Header";

export const dynamic = 'force-dynamic';
export const fetchCache = 'force-no-store';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ApolloClientProvider>
          <AuthProvider>
            <Header />
            {children}
          </AuthProvider>
        </ApolloClientProvider>
      </body>
    </html >
  );
}
