import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/header";
import Footer from "./components/footer";
import ApolloClientProvider from "./providers/ApolloProvider";

const geistSans = localFont({
  src: "/fonts/Geist-ExtraLight.ttf",
  variable: "--font-geist-sans",
});

const geistMono = localFont({
  src: "/fonts/Geist-Medium.ttf",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ApolloClientProvider>
          <Header />
          {children}
          <Footer />
        </ApolloClientProvider>
      </body>
    </html>
  );
}
